### ISSUE TITLE
Add Column for different Platform 

### ISSUE THREAD

**Issue by iamakhileshmishra** [PCON-Hacktoberfest-2022/ClockSet-v1#1]
Currently, this Chrome Extension is Supported for leetcode only. I want the contributor to add Other platforms also.

You can use Kontest.api for other platform coding contest details.

**Comment by shalearkane** [comment]
I want to add column for Codeforces website and TopCoder website, please assign this issue to me.

**Comment by iamakhileshmishra** [comment]
@shalearkane  Are you working on it...

**Comment by shalearkane** [comment]
Yes I am working on it

**Comment by iamakhileshmishra** [comment]
@shalearkane what's your progress tell me otherwise I will assign this to anyone else.

**Comment by Ashish-29** [comment]
I want to add codeforces contest ,please assign it to me.

**Comment by iamakhileshmishra** [comment]
Ok assigning this to you. @Ashish-29

**Comment by priyanshudevsingh** [comment]
I want to add codechef contest, please assign it to me.

**Comment by Angshuman-Pal** [comment]
I want to add KickStart Contest please assign this to me

**Comment by iamakhileshmishra** [comment]
As the Major Contest Platforms have been added I am closing this issue.

Thanks, everyone for contributing to this issue and making our project much more useful.
