### ISSUE TITLE
want to change the footer text

### ISSUE THREAD

**Issue by Subhadiptech** [PCON-Hacktoberfest-2022/ClockSet-v1#14]

**Comment by Subhadiptech** [comment]
Please assign me this issue @iamakhileshmishra

**Comment by JayantDane123** [comment]
Hello sir ,
please assign me for this issues
I ensure to complete it

**Comment by iamakhileshmishra** [comment]
@JayantDane123 Thanks for showing interest in this issue but this issue has been fixed by someone else better if you work on another issue
