### ISSUE TITLE
Want to make the footer remain at the bottom of the page

### ISSUE THREAD

**Issue by Bluebberies** [PCON-Hacktoberfest-2022/ClockSet-v1#16]
Want to make the footer remain at the bottom of the page

**Comment by ZishanAhmad** [comment]
I would like to work on this.Kindly assign this to me.

**Comment by Bluebberies** [comment]
A pull request has been made already for it

**Comment by iamakhileshmishra** [comment]
@Bluebberies Your PR has some Merge Conflicts better resolve it before pushing.

You must take a fresh pull from master before pushing it so that there would be no merge conflicts.

**Comment by iamakhileshmishra** [comment]
I am closing your PR .

**Comment by iamakhileshmishra** [comment]
@ZishanAhmad this is assigned to you Go ahead.
