### ISSUE TITLE
want to change footer style and text 

### ISSUE THREAD

**Issue by anishnitjsr** [PCON-Hacktoberfest-2022/ClockSet-v1#19]
please assign this project

**Comment by iamakhileshmishra** [comment]
Ok Assigning this to you

**Comment by iamakhileshmishra** [comment]
What's the status ??

**Comment by anishnitjsr** [comment]
Sorry sir for taking time .
I got stucked sir but by tomorrow i will pull requests sir .

**Comment by rishav981** [comment]
Please assign this to me I would like  to work upon this issue
