### ISSUE TITLE
Update the UI 

### ISSUE THREAD

**Issue by iamakhileshmishra** [PCON-Hacktoberfest-2022/ClockSet-v1#2]
Use Custom CSS or Bootstrap to make the UI of this Chrome-Extension more Eye Catchy and User friendly

**Comment by Milind-Palaria** [comment]
hey @iamakhileshmishra i would like to contribute to this. can u assign this to me?

**Comment by iamakhileshmishra** [comment]
@Milind-Palaria are you working on it?

**Comment by Milind-Palaria** [comment]
@iamakhileshmishra i will complete the project before 10p.m. today , sorry for the delay.

**Comment by Shubham-codes-docs** [comment]
The ui has been improved

**Comment by Angshuman-Pal** [comment]
Want to work on the footer optimization of this please assign this to me.

**Comment by iamakhileshmishra** [comment]
Thanks for contributing to this issue.
