### ISSUE TITLE
fetch contests dynamically

### ISSUE THREAD

**Issue by ggautamgoyalg** [PCON-Hacktoberfest-2022/ClockSet-v1#23]

**Comment by iamakhileshmishra** [comment]
Can you elaborate the issue upon which you want to work so that I can assign this to you

**Comment by ggautamgoyalg** [comment]
it is showing only 2 contests in list but we can output (or show to user) details of all the contests fetched through api

**Comment by iamakhileshmishra** [comment]
This issue is already created in #1 you can work on this from that issue and ask me to assign on that issue #1.
