### ISSUE TITLE
Change the Timing to IST and in better formnat

### ISSUE THREAD

**Issue by iamakhileshmishra** [PCON-Hacktoberfest-2022/ClockSet-v1#3]
Currently the Timing of the contest are not formated well. Format the Date and time as per Indian time 

From this 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/79476272/193462626-1dd28a63-be7c-4de6-aa45-bc01c93982ef.png">

We want this type of Format
<img width="307" alt="Screenshot 2022-10-02 210712" src="https://user-images.githubusercontent.com/79476272/193462597-8a327abe-0262-48bf-9e8e-97e22eac9bc8.png">

Feel free to comment if unable to understand

**Comment by ManasviGoyal** [comment]
Hi. Can you please elaborate where the timing has been used in the code. I would like to fix it.

**Comment by iamakhileshmishra** [comment]
Go to the contest.js file there is the API call and the API has a attribute as start-time and end time which is being fetched by the API 
[Refer to Kontest Api] so you have to change that in coming time from API to a standard format as shown in the figure

**Comment by iamakhileshmishra** [comment]
Fomate the date and time UI as start time and End time Column

**Comment by s-vamshi** [comment]
#6  
@iamakhileshmishra i have added start and end time column, can you check my PR?

**Comment by iamakhileshmishra** [comment]
Done!!!
Thanks for contributing in this issue now closing this.

**Comment by iamakhileshmishra** [comment]
@22shubh22 While changing the time format to Indian Standard you have broken the date details the month is not correctly displayed now. 

Please check that and raise a PR asap.

**Comment by 22shubh22** [comment]
okay @iamakhileshmishra

**Comment by Shubham-codes-docs** [comment]
The timing has been resolved as well

**Comment by gauriimaheshwarii** [comment]
@iamakhileshmishra The issue is now fixed. Kindly merge my PR #13.

**Comment by iamakhileshmishra** [comment]
@gauriimaheshwarii Your PR has some issues when I try to run it locally it doesn't load up. 
By the way, the issue has been fixed by @Shubham-codes-docs so you can work on another issue present or you can create an issue to work upon.

Keep Coding 🙌🙌
