### ISSUE TITLE
Use LocalStorage For Theme toggler

### ISSUE THREAD

**Issue by iamakhileshmishra** [PCON-Hacktoberfest-2022/ClockSet-v1#31]

**Comment by madmaxWMFU** [comment]
Hi! Can you assign it to me?

**Comment by rishav981** [comment]
hello, I want to work on it can you please assign it to me?

**Comment by iamakhileshmishra** [comment]
This issue has been resolved by @rishav981  @madmaxWMFU you could work on other issue like  #1
