### ISSUE TITLE
Add Filter for different Coding Platform

### ISSUE THREAD

**Issue by iamakhileshmishra** [PCON-Hacktoberfest-2022/ClockSet-v1#35]
Add a button for different platform and once clicked only those coding contest should list

**Comment by NNL-Keerthana** [comment]
Hi!! I am interested to work on this issue. Can you please assign this to me? Also, could you please give some more details.

**Comment by iamakhileshmishra** [comment]
@NNL-Keerthana  first fork and run my project locally there you will find that the leetcode contests and code forces (and later upcoming APIs) all are listed on a page but I want you as a contributor to add an option below the navbar like Codeforces  Leetcode GFG AtCoder etc and once a user click on any tab they see only contests of that platform 

Hint:- You can use Span and play with it.

Let me know if you want to work on it, I will assign this to you

**Comment by NNL-Keerthana** [comment]
I surely want to try.  Pls assign it to me

**Comment by iamakhileshmishra** [comment]
Ok @NNL-Keerthana  Go Ahead assigning this to you 🙌

Don't Forget to give a star if you like this repo.

**Comment by iamakhileshmishra** [comment]
@NNL-Keerthana What's the status...??

**Comment by NNL-Keerthana** [comment]
Will finish by tonight, sry got lil stuck with course work

**Comment by iamakhileshmishra** [comment]
@22shubh22 Hey buddy would you like to work on this issue?

**Comment by 22shubh22** [comment]
sure, please assign me this. I would research and check it. @iamakhileshmishra

**Comment by NNL-Keerthana** [comment]
I am working on it... there some bug and the js files are not loading properly into HTML, which is why its taking time to resolve it and then do my part of it.

**Comment by iamakhileshmishra** [comment]
@NNL-Keerthana No issue you work on it and I will wait till tomorrow for that @22shubh22 will work once you fail to work on that

@NNL-Keerthana What's the issue you are facing you can ping me here I will help you. You have installed the npm dependency. I think that will solve your issue 
Run 
`npm i `

**Comment by Rajiv7479** [comment]
assign me

**Comment by iamakhileshmishra** [comment]
Thank you everyone for showing interest in this issue and working on this as this has been resolved I am closing this issue 

However, I am opening a new issue (#60) with the work to sort the contests as per the contest start time (ascending) So if you guys are interested on the issue can request there to assign I will surely assign it to you after seeing your dedication @NNL-Keerthana @22shubh22 🙌🙌🙌
