### ISSUE TITLE
images are hardcoded in the contest card. Make them flexible.

### ISSUE THREAD

**Issue by 22shubh22** [PCON-Hacktoberfest-2022/ClockSet-v1#37]

**Comment by iamakhileshmishra** [comment]
Good Issue pointed out you can work upon this I am assigning this to you

**Comment by iamakhileshmishra** [comment]
Let me know if you are working on this issue or not else I will assign this to anyone else.
@22shubh22

**Comment by 22shubh22** [comment]
@iamakhileshmishra this can be closed now.
