### ISSUE TITLE
Fix UI bugs 

### ISSUE THREAD

**Issue by iamakhileshmishra** [PCON-Hacktoberfest-2022/ClockSet-v1#45]
![image](https://user-images.githubusercontent.com/79476272/197336947-e9da2c89-32b2-4507-ab51-74c3fb90bc53.png)
![image](https://user-images.githubusercontent.com/79476272/197336964-fdf68b27-85f2-484a-ac3c-44028ca2102b.png)

Solve these UI bugs

**Comment by iamakhileshmishra** [comment]
title should not be like that and Solve the duration pattern

**Comment by taksuparth** [comment]
I can pick this up

**Comment by Aspireve** [comment]
Hi @iamakhileshmishra 
Could I try solving this bug?

**Comment by iamakhileshmishra** [comment]
Go ahead @Aspireve 🙌 assigning this to you

**Comment by iamakhileshmishra** [comment]
What's the update @Aspireve

**Comment by Aspireve** [comment]
Im still trying to do it, gonna take me a bit longer.

**Comment by Aspireve** [comment]
Hi @iamakhileshmishra,
If possible could you explain how your project works, cause I'm not able to recreate the same screen as you have in the screenshot.

**Comment by 123Devapriya** [comment]
i want to work on this.

**Comment by abhishekr700** [comment]
@iamakhileshmishra I would like to contribute, can you assign this to me too ?

**Comment by priyanshudevsingh** [comment]
I think I can solve this bug, can you assign this to me?

**Comment by iamakhileshmishra** [comment]
Okie @PriyanshuSingh033 Assigning this to you.🙌

**Comment by iamakhileshmishra** [comment]
This issue is going to open again for you all and this time there are some UI bugs. You have to consider it as a 300 px width chrome Extension and Design UI as per this so If anyone is interested in this I will assign this to them. If anyone wants to work on this let me know.
