### ISSUE TITLE
Add Theme toogler Dark/Light

### ISSUE THREAD

**Issue by iamakhileshmishra** [PCON-Hacktoberfest-2022/ClockSet-v1#5]
Add an option of theme Toggler for thus extension using localStorage 
Note:- Keep in mind this is a Chrome Extension

**Comment by s-vamshi** [comment]
Hey can you assign this to me?

**Comment by zialink** [comment]
Please assign this issue to me. Thanks

**Comment by 22shubh22** [comment]
@iamakhileshmishra you mean that our extension should change itself to the dark mode or light mode depending on the browser's setting? Right?

https://stackoverflow.com/questions/58880234/toggle-chrome-extension-icon-based-on-light-or-dark-mode-browser

**Comment by zialink** [comment]
I have tried severally to load this repo to chrome extension, but I keep getting an errror that says could load manifest
![chrome_error](https://user-images.githubusercontent.com/16071848/193622094-0799868a-0b71-4895-87f7-dacb2f5301fb.PNG)

**Comment by 22shubh22** [comment]
This seems because stopwatch.js don't exist in the manifest.json @zialink 
@iamakhileshmishra can you change it to relevant file

**Comment by iamakhileshmishra** [comment]
There is no such error when I am running it locally. Please check  you have clone the master repo

**Comment by 22shubh22** [comment]
@iamakhileshmishra 
this line - https://github.com/PCON-Hacktoberfest-2022/ClockSet-v1/blob/master/manifest.json#L17

throws error when extension is loaded in chrome https://www.freecodecamp.org/news/how-to-create-and-publish-a-chrome-extension-in-20-minutes-6dc8395d7153/

**Comment by iamakhileshmishra** [comment]
Issue Resolved by @Shubham-codes-docs
