### ISSUE TITLE
Add Icons of paticular Coding Platform in their Content Box.

### ISSUE THREAD

**Issue by iamakhileshmishra** [PCON-Hacktoberfest-2022/ClockSet-v1#9]

**Comment by deepesh16b** [comment]
Please assign this to me
I can add that icons

**Comment by joanjeremiah** [comment]
I would like to solve this issue. Kindly assign this to me.

**Comment by Shamik1836** [comment]
I would like to work on this issue, kindly assign this to me

**Comment by iamakhileshmishra** [comment]
@joanjeremiah @Shamik1836 this issue is assigned to someone else you can look at other issue like #1

**Comment by deepesh16b** [comment]
Sir,
There's only leetcode contest on the website

**Comment by deepesh16b** [comment]
> Sir,
> There's only leetcode contest on the website

So I am adding it's icon

**Comment by deepesh16b** [comment]
@iamakhileshmishra 
Please check if it is ok or not
![a](https://user-images.githubusercontent.com/70226498/194126398-5b251e19-8bbe-4cf0-93bf-e2b9b5227dc5.jpg)
![Screenshot 2022-10-05 231114](https://user-images.githubusercontent.com/70226498/194126422-8505db77-9619-4d7c-a0a5-072e98340044.jpg)

**Comment by 22shubh22** [comment]
@deepesh16b please push the changes and make a PR for the same.

**Comment by deepesh16b** [comment]
> @deepesh16b please push the changes and make a PR for the same.

@iamakhileshmishra 
I have made a new PR

**Comment by 22shubh22** [comment]
@deepesh16b  you can associate your PR with the GitHub issue. Please do that in the future.

**Comment by 22shubh22** [comment]
@iamakhileshmishra this can be closed now

**Comment by iamakhileshmishra** [comment]
Ya Sure 🙌🙌
